### PR TITLE
Add more test coverage to cover remaining cases

### PR DESCRIPTION
**Pull request by takikawa**
* Add more tests for VLQ parsing
  * Add type correctness tests for remaining fields
  * Add more index map tests
  * Add tests related to source resolution
  * Add more tests for mapping semantics

Some cases that are still missing:

  * Tests for Wasm, CSS, etc. sources
  * Tests for relative URL resolution (it wasn't clear how best to integrate into test harnesses)

### CODE REVIEW

**Review by jkup — APPROVED** [review]
These look great!

Some of them are very easy to understand like "file-not-a-string" and some of them could use some context like "valid-continuation-bit-present". I wonder if it would be good to have some place where we better describe why it's important or which part of the spec it refers to?

I haven't run these locally, but I'm just curious, do we have anything checking for why source maps fail? Like I see we mark them as should pass or not but curious if we could have bugs where a meant to fail test is failing for the wrong reason.

Thanks for doing these!

**Comment by takikawa** [comment]
Thanks for taking a look!

> Some of them are very easy to understand like "file-not-a-string" and some of them could use some context like "valid-continuation-bit-present". I wonder if it would be good to have some place where we better describe why it's important or which part of the spec it refers to?

Yeah, I think more info could be useful. Right now the intention is that the "description" field in the test info JSON file provides some info as an arbitrary string. Do you think expanding those with a bit more info, like references to the spec, would be enough?

> I haven't run these locally, but I'm just curious, do we have anything checking for why source maps fail? Like I see we mark them as should pass or not but curious if we could have bugs where a meant to fail test is failing for the wrong reason.

Currently no, the validity checks are just binary fail or succeed. I think it could be useful to have more fine-grained specifications here, but there's a lot of variation in how much error reporting that implementations do. Maybe one option would be to try to broadly categorize errors like "vlq-parsing", "missing-element", "out-of-bounds", etc. and let test harnesses interpret those (or ignore them) as they like.

**Comment by takikawa** [comment]
I went ahead and merged this but can follow up with improvements based on the discussion

**Comment by jkup** [comment]
1. I think that's a great idea! I wonder if we could just add a field to link to the relevant spec text?
2. Makes sense to me! That's what I thought, I was just checking. Would be cool to categorize them but I don't think that's needed right now!

**Pull request merged**
